### ISSUE TITLE
Scrypt - Block cant be decoded

### ISSUE THREAD

**Issue by nitrocon** [Butkoin/but#15]
ERROR: rpc_do_call: 127.0.0.1:10016 500 22:15:51: ERROR Butkoin Block decode failed 22:15:51: *** REJECTED :( Butkoin block 5674 2 txs

on every block found...mining scrypt with a nvidia GPU

**Comment by ALEX8731971** [comment]
found by goromil report on discord

The bug is there in block.cpp, line 58, method uint256 CBlockHeader::GetPOWHash(int algo),
default:
            scrypt_1024_1_1_256(BEGIN(nVersion), BEGIN(thash));
            return thash; // <<-- this is missing
    }
    return GetHash();
