### ISSUE TITLE
i got this issue when i do make

### ISSUE THREAD

**Issue by afiniel** [Butkoin/but#3]
CXX      bls/libbutconsensus_la-bls.lo
In file included from bls/bls.cpp:6:0:
bls/bls.h:15:10: fatal error: chiabls/bls.hpp: No such file or directory
 #include <chiabls/bls.hpp>

**Comment by Butkoin** [comment]
wget https://github.com/ButKoin/bls-signatures/archive/v20181101.zip
mkdir build
cd build
cmake ../
cmake --build . 
sudo make install
then build again
