### ISSUE TITLE
Hi! I download the wallet for windows 64. It start, but cant connect to the network.

### ISSUE THREAD

**Issue by SRGIO-02** [Butkoin/but#8]
This issue tracker is only for technical issues related to But Core.

General But questions and/or support requests and are best directed to the [But Reddit](https://www.reddit.com/r/but/).

To report critical security issues, email infosec@butcoin.tech and/or see the BUT bug bounty program on [Bugcrowd](https://bugcrowd.com/butdigitalcash) instead of creating Github issues.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of But Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by SRGIO-02** [comment]
I download the wallet for windows 64 version (v1.2.16.3-19118946d-dirty).
It cant connect to the network.
![image](https://user-images.githubusercontent.com/93764992/140487578-ad26020f-0268-4a19-8399-0cd913931d92.png)

**Comment by chongada** [comment]
add this nodes below but in the next release it will connect automatically

```text
addnode=51.161.32.104:24240
addnode=39.98.125.170:24240
addnode=86.57.193.186:24240
addnode=74.74.76.149:9415
addnode=39.98.123.66:24240
addnode=218.95.36.11:42544
addnode=95.129.140.52:21171
addnode=158.247.203.201:24240
addnode=162.55.0.83:35254
addnode=167.179.75.144:47996
addnode=105.242.70.229:33880
addnode=108.61.161.81:24240
addnode=188.186.4.98:14751
addnode=74.74.76.149:33117
addnode=[2400:4052:1400:3b00:4045:ee62:5633:f5cb]:50433
addnode=108.175.14.116:33554
addnode=62.171.150.191:43132
addnode=146.59.185.77:42384
addnode=46.37.79.111:54244
addnode=46.37.79.111:48716
addnode=168.119.109.236:42194
addnode=160.152.27.235:59829
addnode=[2a01:4f8:c010:8d90::1]:24240
addnode=59.172.88.61:35234
addnode=74.74.76.149:59136
addnode=94.247.63.109:46752
addnode=218.95.36.11:59782
addnode=94.247.63.173:19407
addnode=[2a01:4f8:1c17:7e04::1]:42390
addnode=157.90.250.169:24240
addnode=154.3.40.201:33159
addnode=87.229.11.188:51606
addnode=88.99.87.177:40540
addnode=188.165.137.90:50394
```

**Comment by yorianlara** [comment]
Hello, I have the same problem, I downloaded the 64-bit wallet and it did not connect ... I already added the nodes through the debugging console and it still does not connect .. am I doing something wrong?

![butkoin_02](https://user-images.githubusercontent.com/23194687/141674221-9a89cb35-5a58-4b09-9ba3-f9984810c69d.png)

![butkoin_01](https://user-images.githubusercontent.com/23194687/141674042-9d1ee8c4-5faf-4968-9ad5-5e3e2371221d.png)

![butkoin_03](https://user-images.githubusercontent.com/23194687/141674258-e462ee91-599f-435b-9bfd-408fe1fe627f.png)

**Comment by yorianlara** [comment]
Machine specs:
OS: Windows 10 Pro 21H1
CPU: Intel Core i5-5200U CPU @ 2.20GHz.
RAM: 4,00 GB
Disk size: 500 GB

**Comment by GBDownUnder** [comment]
> Hello, I have the same problem, I downloaded the 64-bit wallet and it did not connect ... I already added the nodes through the debugging console and it still does not connect .. am I doing something wrong?
> 

Yep me to man

**Comment by GBDownUnder** [comment]
> > Hello, I have the same problem, I downloaded the 64-bit wallet and it did not connect ... I already added the nodes through the debugging console and it still does not connect .. am I doing something wrong?
> 
> Yep me to man

Can't open any of those ports on any of those IPs listed.  Seems everyone has turned them off.

**Comment by yorianlara** [comment]
> > > Hello, I have the same problem, I downloaded the 64-bit wallet and it did not connect ... I already added the nodes through the debugging console and it still does not connect .. am I doing something wrong?
> > 
> > 
> > Yep me to man
> 
> Can't open any of those ports on any of those IPs listed. Seems everyone has turned them off.


I used the android wallet and it worked for me

**Comment by zumy5** [comment]
Hello, I have the same problem, I downloaded the 64-bit wallet and it did not connect 1.2.17.3?

**Comment by zumy5** [comment]
WINDOWS 11

**Comment by GBDownUnder** [comment]
Consider it a favor, the project is a joke.  All you need to do is hint at questioning the direction of the project and you get banned on discord.  Lets face it, any coin called But is an anal joke and will never be worth anything, that's ignoring the whole original BUT coin completely failing and having to change it to BUTK coin and basically trash any coins anyone owned who wasn't active on their discord and found out how they had to move their coins around to get them converted.  Complete and utter SCAM.

**Comment by zumy5** [comment]
well thank you

**Comment by zumy5** [comment]
thank you for your opinion, i would need nodes.

**Comment by zumy5** [comment]
Config file for wallet, any node?1.217.3 Wallet win 64...
